### ISSUE TITLE
Make the cli nicer

### ISSUE THREAD

**Issue by lu-zero** [loganek/hawktracer-converter#4]
Since it is using clap would be nice to:
- have short arguments (e.g. `-s`, `-o`).
- have defaults for the format (e.g. default to chrome-tracing)

I can send a PR if there is consensus in having the above.

**Comment by loganek** [comment]
@lu-zero I agree with your suggestions, feel free to raise the CR if you want :)

**Comment by loganek** [comment]
Code merged, closing the ticket.
